categories:
  - title: "🚀 Features"
    label: "features"
  - title: "🤖 Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📝 Document"
    label: "documentation"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
template: |
  ## ✨Changes
  $CHANGES
