name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
      - run: yarn tsc --noEmit
      - run: yarn prettier --check src
      - run: yarn eslint src
      - run: yarn build
